### PR TITLE
Faster point label placement for simple polygons using centroid

### PR DESCRIPTION
**Pull request by lukasmartinelli**
Resolves https://github.com/mapbox/postgis-vt-util/issues/18.
@ajashton we could put it into a separate function but I think this works good enough to make it the default for calculating labels using topoint.

### CODE REVIEW

**Comment by ajashton** [comment]
I'm fine merging this as-is, but if it's just as performant to also check for <5-pointed single-member multipolygons that would be great. For example, nearly all polygons going through Mapbox Streets are actually multipolygons even if they don't need to be.

**Comment by lukasmartinelli** [comment]
> For example, nearly all polygons going through Mapbox Streets are actually multipolygons even if they don't need to be.

👍 The same approach should work for MultiPolygon. Let me write more tests for this to capture simple (<=5) and complex (>5) polygons + multipolygons and then I merge this!

**Comment by pnorman** [comment]
Would it not make more sense to send this upstream to PostGIS?

**Comment by lukasmartinelli** [comment]
Things left to do:
- [ ] Research whether PostGIS does this optimization already internally and if not why not
- [ ] Add more tests with complex and simple polygons
- [ ] Run a speed comparison on a large dataset (we already have some number that show it is faster)
- [ ] Check how it works with multipolygons

**Comment by lukasmartinelli** [comment]
> Research whether PostGIS does this optimization already internally and if not why not

It's a straight GEOS call
https://github.com/postgis/postgis/blob/bd3177743db5cb786deb05d7327f39a5cec2daf6/postgis/lwgeom_geos.c#L1241
https://trac.osgeo.org/geos/browser/trunk/src/algorithm/InteriorPointArea.cpp?rev=3781

it doesn't do this optimization (which makes sense because it doesn't apply to all polygon types and this function guarantees that the point lies on the surface area).

**Comment by lukasmartinelli** [comment]
Uuhm I got a 2-3x times speed up. Can't really believe the number is that high. Rerunning a test again but it is definitely faster not slower.

**Pull request merged**
